name: Fat ecto tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    

    steps:
    - uses: actions/checkout@v1.0.0
    - uses: actions/setup-elixir@v1.0.0
    - name: Set up elixir 1.9
      with: 
            otp-version: 22.x
            elixir_version: 1.9.x

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
    env:
        PGHOST: localhost
        PGUSER: postgres
        Elixir_ENV: test
    run: |
          MIX_ENV=test mix ecto.create
          MIX_ENV=test mix ecto.migrate
          mix test
